export const INITIALIZE_INGREDIENTS = 'INITIALIZE_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const POST_ORDER_STARTED = 'POST_ORDER_STARTED';
export const POST_ORDER_SUCCEEDED = 'POST_ORDER_SUCCEEDED';
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDER_STARTED = 'FETCH_ORDER_STARTED';
export const FETCH_ORDER_SUCCEEDED = 'FETCH_ORDER_SUCCEEDED';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED';

export const AUTH_STARTED = 'AUTH_STARTED';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';